# Generated by Django 5.2.13 on 2026-04-17 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptosBasicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('concepto', models.CharField(max_length=100)),
                ('ejemplo', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_fuente', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('editorial', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('fecha_consulta', models.DateField()),
                ('descripcion', models.TextField()),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Formulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('expresion', models.TextField()),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Practicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_practica', models.CharField(max_length=100)),
                ('concepto', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('descripcion', models.TextField()),
                ('materiales', models.TextField()),
                ('calculos', models.TextField()),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muestras', models.TextField()),
                ('calculos', models.TextField()),
                ('resultados', models.TextField()),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorio')),
            ],
        ),
    ]
