# Generated by Django 6.0.3 on 2026-04-14 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliografia',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorio'),
        ),
        migrations.AddField(
            model_name='formulas',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorio'),
        ),
        migrations.AddField(
            model_name='practicas',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorio'),
        ),
        migrations.AddField(
            model_name='procedimientos',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorio'),
        ),
    ]
