# Generated by Django 6.0.4 on 2026-06-07 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_recursos_conceptosbasicos_recursos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicas',
            name='concepto',
        ),
        migrations.AddField(
            model_name='practicas',
            name='conceptos',
            field=models.ManyToManyField(to='contenido.conceptosbasicos'),
        ),
        migrations.CreateModel(
            name='PracticaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.practicas')),
            ],
            options={
                'unique_together': {('estudiante', 'practica')},
            },
        ),
    ]
