# Generated by Django 6.0.4 on 2026-06-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_remove_practicas_concepto_practicas_conceptos_and_more'),
        ('laboratorios', '0013_remove_detalleactividad_actividad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaBibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_fuente', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField()),
                ('editorial', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('fecha_consulta', models.DateField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('expresion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_practica', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('descripcion', models.TextField()),
                ('materiales', models.TextField()),
                ('calculos', models.TextField()),
            ],
            options={
                'ordering': ['nombre_practica'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muestras', models.TextField()),
                ('calculos', models.TextField()),
                ('resultados', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_practica', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('descripcion', models.TextField()),
                ('materiales', models.TextField()),
                ('calculos', models.TextField()),
            ],
            options={
                'ordering': ['nombre_practica'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muestras', models.TextField()),
                ('calculos', models.TextField()),
                ('resultados', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='formulas',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='practicas',
            name='conceptos',
        ),
        migrations.RemoveField(
            model_name='practicas',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='procedimientos',
            name='laboratorio',
        ),
        migrations.AlterModelOptions(
            name='bibliografia',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterModelOptions(
            name='conceptosbasicos',
            options={'ordering': ['concepto']},
        ),
        migrations.RemoveField(
            model_name='conceptosbasicos',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='bibliografia',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bibliografia',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliografias', to='laboratorios.laboratorio'),
        ),
        migrations.AlterField(
            model_name='practicaestudiante',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('expresion', models.TextField()),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='laboratorios.laboratorio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
