# Generated by Django 6.0.4 on 2026-06-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_plantillabibliografia_plantillaformula_and_more'),
        ('laboratorios', '0014_alter_etapa_options_alter_laboratorio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillabibliografia',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliografias', to='laboratorios.plantillalaboratorio'),
        ),
        migrations.AddField(
            model_name='plantillaformula',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='laboratorios.plantillalaboratorio'),
        ),
        migrations.AddField(
            model_name='plantillapractica',
            name='conceptos',
            field=models.ManyToManyField(blank=True, related_name='practicas_plantilla', to='contenido.conceptosbasicos'),
        ),
        migrations.AddField(
            model_name='plantillapractica',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='laboratorios.plantillalaboratorio'),
        ),
        migrations.AddField(
            model_name='plantillaprocedimiento',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='laboratorios.plantillalaboratorio'),
        ),
        migrations.AddField(
            model_name='practica',
            name='conceptos',
            field=models.ManyToManyField(blank=True, related_name='practicas', to='contenido.conceptosbasicos'),
        ),
        migrations.AddField(
            model_name='practica',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='laboratorios.laboratorio'),
        ),
        migrations.AlterField(
            model_name='practicaestudiante',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas_estudiantes', to='contenido.practica'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='laboratorios.laboratorio'),
        ),
        migrations.DeleteModel(
            name='Formulas',
        ),
        migrations.DeleteModel(
            name='Procedimientos',
        ),
        migrations.DeleteModel(
            name='Practicas',
        ),
    ]
