# Generated by Django 6.0.4 on 2026-06-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_plantillabibliografia_plantilla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillabibliografia',
            name='plantilla',
        ),
        migrations.AlterField(
            model_name='practicaestudiante',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.DeleteModel(
            name='Bibliografia',
        ),
        migrations.DeleteModel(
            name='PlantillaBibliografia',
        ),
    ]
