# Generated by Django 6.0.4 on 2026-06-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_plantillabibliografia_plantilla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillabibliografia',
            name='plantilla',
        ),
        migrations.AlterModelOptions(
            name='plantillaprocedimiento',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='procedimiento',
            options={'ordering': ['orden']},
        ),
        migrations.RenameField(
            model_name='plantillaprocedimiento',
            old_name='calculos',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='procedimiento',
            old_name='calculos',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='plantillaprocedimiento',
            name='muestras',
        ),
        migrations.RemoveField(
            model_name='plantillaprocedimiento',
            name='resultados',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='muestras',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='resultados',
        ),
        migrations.AddField(
            model_name='plantillaprocedimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='procedimientos/'),
        ),
        migrations.AddField(
            model_name='plantillaprocedimiento',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantillaprocedimiento',
            name='paso_numero',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='procedimientos/'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='paso_numero',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practicaestudiante',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.DeleteModel(
            name='Bibliografia',
        ),
        migrations.DeleteModel(
            name='PlantillaBibliografia',
        ),
    ]
