# Generated by Django 6.0.4 on 2026-06-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_plantillabibliografia_plantilla_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillaprocedimiento',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='procedimiento',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveField(
            model_name='plantillaprocedimiento',
            name='calculos',
        ),
        migrations.RemoveField(
            model_name='plantillaprocedimiento',
            name='muestras',
        ),
        migrations.RemoveField(
            model_name='plantillaprocedimiento',
            name='resultados',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='calculos',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='muestras',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='resultados',
        ),
        migrations.AddField(
            model_name='plantillaprocedimiento',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantillaprocedimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='procedimientos/'),
        ),
        migrations.AddField(
            model_name='plantillaprocedimiento',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantillaprocedimiento',
            name='paso_numero',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='procedimientos/'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='paso_numero',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
