# Generated by Django 6.0.4 on 2026-06-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_remove_plantillabibliografia_plantilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaestudiante',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20),
        ),
    ]
