# Generated by Django 6.0.4 on 2026-06-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_alter_practicaestudiante_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicaestudiante',
            name='estado',
        ),
    ]
