# Generated by Django 6.0.4 on 2026-06-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_remove_practicaestudiante_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillapractica',
            name='conceptos',
        ),
        migrations.RemoveField(
            model_name='plantillapractica',
            name='plantilla',
        ),
        migrations.RemoveField(
            model_name='plantillaprocedimiento',
            name='plantilla',
        ),
        migrations.DeleteModel(
            name='PlantillaFormula',
        ),
        migrations.DeleteModel(
            name='PlantillaPractica',
        ),
        migrations.DeleteModel(
            name='PlantillaProcedimiento',
        ),
    ]
