# Generated by Django 6.0.4 on 2026-07-05 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_remove_plantillapractica_conceptos_and_more'),
        ('laboratorios', '0028_remove_laboratorio_conceptos_basicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptosbasicos',
            name='recursos',
        ),
        migrations.RemoveField(
            model_name='recursos',
            name='archivo',
        ),
        migrations.CreateModel(
            name='ConceptoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='contenido.conceptosbasicos')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_laboratorio', to='laboratorios.laboratorio')),
                ('recursos', models.ManyToManyField(blank=True, related_name='conceptos_laboratorio', to='contenido.recursos')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('laboratorio', 'concepto'), name='unique_concepto_laboratorio')],
            },
        ),
    ]
