# Generated by Django 6.0.4 on 2026-07-05 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0010_remove_conceptosbasicos_recursos_and_more'),
        ('laboratorios', '0028_remove_laboratorio_conceptos_basicos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conceptolaboratorio',
            name='unique_concepto_laboratorio',
        ),
        migrations.AddField(
            model_name='conceptolaboratorio',
            name='concepto_original',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos_originales', to='contenido.conceptosbasicos'),
        ),
        migrations.AddField(
            model_name='conceptolaboratorio',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptolaboratorio',
            name='ejemplo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptolaboratorio',
            name='tipo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptolaboratorio',
            name='concepto',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='conceptolaboratorio',
            constraint=models.UniqueConstraint(fields=('laboratorio', 'concepto_original'), name='unique_concepto_laboratorio'),
        ),
    ]
