# Generated by Django 6.0.4 on 2026-07-08 21:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0011_remove_conceptolaboratorio_unique_concepto_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='archivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
