# Generated by Django 6.0.4 on 2026-07-09 01:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0012_recursos_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='archivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
