# Generated by Django 6.0.4 on 2026-07-10 02:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0013_alter_recursos_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
