# Generated by Django 6.0.3 on 2026-04-16 19:53

from django.db import migrations

def crear_parametros(apps, schema_editor):
    Parametro = apps.get_model('parametros', 'Parametro')
    datos = [
        ('ROLE_ESTUDIANTE', 'estudiante'),
        ('ROL_SUPERADMIN', 'superadmin'),
        ('ROL_PROFESOR', 'profesor'),
        ('ROL_ADMIN', 'admin'),
    ]
    for clave, valor in datos:
        Parametro.objects.get_or_create(clave=clave, defaults={'valor': valor})

def revertir_parametros(apps, schema_editor):
    Parametro = apps.get_model('parametros', 'Parametro')
    Parametro.objects.filter(clave__in=[
        'ROLE_ESTUDIANTE',
        'ROL_SUPERADMIN',
        'ROL_PROFESOR',
        'ROL_ADMIN',
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_parametros, revertir_parametros),
    ]