# Generated by Django 6.0.3 on 2026-04-16 20:44

from django.db import migrations

def corregir_parametros(apps, schema_editor):
    Parametro = apps.get_model('parametros', 'Parametro')
    correcciones = [
        ('ROL_ADMIN', 'ROLE_ADMIN', 'admin'),
        ('ROL_SUPERADMIN', 'ROLE_SUPERADMIN', 'superadmin'),
        ('ROL_PROFESOR', 'ROLE_PROFESOR', 'profesor'),
    ]
    for clave_vieja, clave_nueva, valor in correcciones:
        Parametro.objects.filter(clave=clave_vieja).update(clave=clave_nueva, valor=valor)

class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_cargar_parametros'),
    ]

    operations = [
        migrations.RunPython(corregir_parametros, migrations.RunPython.noop),
    ]