# Generated by Django 6.0.4 on 2026-04-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_corregir_parametros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
