# Generated by Django 6.0.4 on 2026-04-23 14:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_embedded_alter_users_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
