# Generated by Django 6.0.4 on 2026-04-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='autorizacion_datos',
            field=models.BooleanField(default=False),
        ),
    ]
