# Generated by Django 6.0.3 on 2026-04-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('administrador', 'Admin'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], default='estudiante', max_length=20),
        ),
    ]
