# Generated by Django 6.0.4 on 2026-05-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_autorizacion_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='embedded',
        ),
    ]
