# Generated by Django 6.0.4 on 2026-05-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_embedded'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='embedded',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
