# Generated by Django 6.0.3 on 2026-04-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_is_active_users_is_staff_users_is_superuser_and_more'),
        ('users', '0005_users_groups_users_is_superuser_and_more'),
    ]

    operations = [
    ]
