# Generated by Django 6.0.4 on 2026-06-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_embedded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='users',
            old_name='embedded',
            new_name='embedding_facial',
        ),
        migrations.AddField(
            model_name='users',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
