# Generated by Django 6.0.4 on 2026-06-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='apellido',
        ),
    ]
