--
-- PostgreSQL database dump
--

\restrict R9xSIs6nin8nATeOphHvtyXLN1oe6kiczJ9v1719y4NuW08yXYBELaeNHCv8SRE

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contenido_bibliografia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contenido_bibliografia (
    id bigint NOT NULL,
    autor character varying(100) NOT NULL,
    titulo character varying(200) NOT NULL,
    tipo_fuente character varying(100) NOT NULL,
    anio integer NOT NULL,
    editorial character varying(150) NOT NULL,
    url character varying(200) NOT NULL,
    fecha_consulta date NOT NULL,
    descripcion text NOT NULL,
    laboratorio_id bigint NOT NULL
);


ALTER TABLE public.contenido_bibliografia OWNER TO postgres;

--
-- Name: contenido_bibliografia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contenido_bibliografia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contenido_bibliografia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contenido_conceptosbasicos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contenido_conceptosbasicos (
    id bigint NOT NULL,
    descripcion text NOT NULL,
    concepto character varying(100) NOT NULL,
    ejemplo text NOT NULL,
    tipo character varying(50) NOT NULL,
    fecha date NOT NULL
);


ALTER TABLE public.contenido_conceptosbasicos OWNER TO postgres;

--
-- Name: contenido_conceptosbasicos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contenido_conceptosbasicos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contenido_conceptosbasicos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contenido_conceptosbasicos_recursos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contenido_conceptosbasicos_recursos (
    id bigint NOT NULL,
    conceptosbasicos_id bigint CONSTRAINT contenido_conceptosbasicos_recurso_conceptosbasicos_id_not_null NOT NULL,
    recursos_id bigint NOT NULL
);


ALTER TABLE public.contenido_conceptosbasicos_recursos OWNER TO postgres;

--
-- Name: contenido_conceptosbasicos_recursos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contenido_conceptosbasicos_recursos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contenido_conceptosbasicos_recursos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contenido_formulas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contenido_formulas (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL,
    expresion text NOT NULL,
    laboratorio_id bigint NOT NULL
);


ALTER TABLE public.contenido_formulas OWNER TO postgres;

--
-- Name: contenido_formulas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contenido_formulas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contenido_formulas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contenido_practicas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contenido_practicas (
    id bigint NOT NULL,
    nombre_practica character varying(100) NOT NULL,
    concepto character varying(100) NOT NULL,
    objetivo text NOT NULL,
    descripcion text NOT NULL,
    materiales text NOT NULL,
    calculos text NOT NULL,
    laboratorio_id bigint NOT NULL
);


ALTER TABLE public.contenido_practicas OWNER TO postgres;

--
-- Name: contenido_practicas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contenido_practicas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contenido_practicas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contenido_procedimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contenido_procedimientos (
    id bigint NOT NULL,
    muestras text NOT NULL,
    calculos text NOT NULL,
    resultados text NOT NULL,
    laboratorio_id bigint NOT NULL
);


ALTER TABLE public.contenido_procedimientos OWNER TO postgres;

--
-- Name: contenido_procedimientos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contenido_procedimientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contenido_procedimientos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contenido_recursos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contenido_recursos (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    archivo character varying(100),
    url character varying(200)
);


ALTER TABLE public.contenido_recursos OWNER TO postgres;

--
-- Name: contenido_recursos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contenido_recursos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contenido_recursos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: informes_conclusiones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.informes_conclusiones (
    id bigint NOT NULL,
    descripcion text NOT NULL,
    importancia character varying(50) NOT NULL,
    fecha date NOT NULL,
    informe_id bigint NOT NULL
);


ALTER TABLE public.informes_conclusiones OWNER TO postgres;

--
-- Name: informes_conclusiones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.informes_conclusiones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.informes_conclusiones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: informes_informe; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.informes_informe (
    id bigint NOT NULL,
    desarrollo text NOT NULL,
    analisis text NOT NULL,
    fecha date NOT NULL,
    autor_id bigint NOT NULL,
    laboratorio_id bigint NOT NULL
);


ALTER TABLE public.informes_informe OWNER TO postgres;

--
-- Name: informes_informe_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.informes_informe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.informes_informe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: informes_recomendaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.informes_recomendaciones (
    id bigint NOT NULL,
    descripcion text NOT NULL,
    prioridad character varying(50) NOT NULL,
    fecha date NOT NULL,
    informe_id bigint NOT NULL
);


ALTER TABLE public.informes_recomendaciones OWNER TO postgres;

--
-- Name: informes_recomendaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.informes_recomendaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.informes_recomendaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: informes_resultado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.informes_resultado (
    id bigint NOT NULL,
    valor double precision NOT NULL,
    unidad character varying(50) NOT NULL,
    instrumento character varying(100) NOT NULL,
    observaciones text NOT NULL,
    fecha date NOT NULL,
    informe_id bigint NOT NULL
);


ALTER TABLE public.informes_resultado OWNER TO postgres;

--
-- Name: informes_resultado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.informes_resultado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.informes_resultado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inscripciones_inscripcion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inscripciones_inscripcion (
    id bigint NOT NULL,
    fecha_inscripcion date NOT NULL,
    laboratorio_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.inscripciones_inscripcion OWNER TO postgres;

--
-- Name: inscripciones_inscripcion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inscripciones_inscripcion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inscripciones_inscripcion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_actividadlaboratorio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_actividadlaboratorio (
    id bigint NOT NULL,
    nivel character varying(20) NOT NULL,
    descripcion text NOT NULL,
    generado_ia boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    laboratorio_id bigint NOT NULL
);


ALTER TABLE public.laboratorios_actividadlaboratorio OWNER TO postgres;

--
-- Name: laboratorios_actividadlaboratorio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_actividadlaboratorio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_actividadlaboratorio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_categoria (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    descripcion text
);


ALTER TABLE public.laboratorios_categoria OWNER TO postgres;

--
-- Name: laboratorios_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_detalleactividad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_detalleactividad (
    id bigint NOT NULL,
    objetivo_especifico text NOT NULL,
    materiales jsonb NOT NULL,
    procedimiento jsonb NOT NULL,
    formula text,
    tiempo_estimado character varying(50) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    actividad_id bigint NOT NULL
);


ALTER TABLE public.laboratorios_detalleactividad OWNER TO postgres;

--
-- Name: laboratorios_detalleactividad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_detalleactividad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_detalleactividad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_etapa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_etapa (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    orden integer NOT NULL,
    laboratorio_id bigint NOT NULL
);


ALTER TABLE public.laboratorios_etapa OWNER TO postgres;

--
-- Name: laboratorios_etapa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_etapa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_etapa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_laboratorio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_laboratorio (
    id bigint NOT NULL,
    titulo_lab character varying(200) NOT NULL,
    codigo_lab character varying(50) NOT NULL,
    resumen text NOT NULL,
    prologo text,
    introduccion text NOT NULL,
    marco_teorico text NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    categoria_id bigint NOT NULL,
    creador_id bigint NOT NULL,
    objetivo_id bigint NOT NULL
);


ALTER TABLE public.laboratorios_laboratorio OWNER TO postgres;

--
-- Name: laboratorios_laboratorio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_laboratorio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_laboratorio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_laboratorio_palabras_clave; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_laboratorio_palabras_clave (
    id bigint NOT NULL,
    laboratorio_id bigint NOT NULL,
    palabraclave_id bigint CONSTRAINT laboratorios_laboratorio_palabras_clav_palabraclave_id_not_null NOT NULL
);


ALTER TABLE public.laboratorios_laboratorio_palabras_clave OWNER TO postgres;

--
-- Name: laboratorios_laboratorio_palabras_clave_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_laboratorio_palabras_clave ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_laboratorio_palabras_clave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_laboratorioprofesor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_laboratorioprofesor (
    id bigint NOT NULL,
    codigo_lab character varying(10) NOT NULL,
    resumen text NOT NULL,
    prologo text,
    introduccion text NOT NULL,
    marco_teorico text NOT NULL,
    generado_ia boolean NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    laboratorio_id bigint NOT NULL,
    profesor_id bigint NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    grado character varying(25),
    jornada character varying(25),
    simulacion boolean NOT NULL
);


ALTER TABLE public.laboratorios_laboratorioprofesor OWNER TO postgres;

--
-- Name: laboratorios_laboratorioprofesor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_laboratorioprofesor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_laboratorioprofesor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_laboratorioprofesor_recursos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_laboratorioprofesor_recursos (
    id bigint NOT NULL,
    laboratorioprofesor_id bigint CONSTRAINT laboratorios_laboratorioprofeso_laboratorioprofesor_id_not_null NOT NULL,
    recursos_id bigint NOT NULL
);


ALTER TABLE public.laboratorios_laboratorioprofesor_recursos OWNER TO postgres;

--
-- Name: laboratorios_laboratorioprofesor_recursos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_laboratorioprofesor_recursos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_laboratorioprofesor_recursos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_objetivo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_objetivo (
    id bigint NOT NULL,
    tipo_objetivo character varying(100) NOT NULL,
    descripcion_objetivo text NOT NULL
);


ALTER TABLE public.laboratorios_objetivo OWNER TO postgres;

--
-- Name: laboratorios_objetivo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_objetivo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_objetivo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_palabraclave; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_palabraclave (
    id bigint NOT NULL,
    palabra_clave character varying(100) NOT NULL,
    descripcion text NOT NULL,
    categoria_id bigint NOT NULL
);


ALTER TABLE public.laboratorios_palabraclave OWNER TO postgres;

--
-- Name: laboratorios_palabraclave_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_palabraclave ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_palabraclave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratorios_progresoestudiante; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios_progresoestudiante (
    id bigint NOT NULL,
    completada boolean NOT NULL,
    fecha_completado date,
    estudiante_id bigint NOT NULL,
    etapa_id bigint NOT NULL
);


ALTER TABLE public.laboratorios_progresoestudiante OWNER TO postgres;

--
-- Name: laboratorios_progresoestudiante_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios_progresoestudiante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_progresoestudiante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notificaciones_log (
    id bigint NOT NULL,
    accion character varying(100) NOT NULL,
    descripcion text NOT NULL,
    fecha timestamp with time zone NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.notificaciones_log OWNER TO postgres;

--
-- Name: notificaciones_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notificaciones_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones_notificacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notificaciones_notificacion (
    id bigint NOT NULL,
    mensaje text NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.notificaciones_notificacion OWNER TO postgres;

--
-- Name: notificaciones_notificacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notificaciones_notificacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_notificacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parametros_parametro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parametros_parametro (
    id bigint NOT NULL,
    clave character varying(100) NOT NULL,
    valor character varying(255) NOT NULL
);


ALTER TABLE public.parametros_parametro OWNER TO postgres;

--
-- Name: parametros_parametro_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parametros_parametro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parametros_parametro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reportes_reportelaboratorio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reportes_reportelaboratorio (
    id bigint NOT NULL,
    estado_informe character varying(20) NOT NULL,
    fecha_creacion date NOT NULL,
    reporte_estudiante character varying(100),
    observaciones_docente text,
    informe_final character varying(100),
    laboratorio_profesor_id bigint NOT NULL
);


ALTER TABLE public.reportes_reportelaboratorio OWNER TO postgres;

--
-- Name: reportes_reportelaboratorio_estudiantes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reportes_reportelaboratorio_estudiantes (
    id bigint NOT NULL,
    reportelaboratorio_id bigint CONSTRAINT reportes_reportelaboratorio_estu_reportelaboratorio_id_not_null NOT NULL,
    users_id bigint NOT NULL
);


ALTER TABLE public.reportes_reportelaboratorio_estudiantes OWNER TO postgres;

--
-- Name: reportes_reportelaboratorio_estudiantes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reportes_reportelaboratorio_estudiantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reportes_reportelaboratorio_estudiantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reportes_reportelaboratorio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reportes_reportelaboratorio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reportes_reportelaboratorio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    nombre character varying(100) NOT NULL,
    fecha_nacimiento date,
    identificacion character varying(20),
    correo character varying(254) NOT NULL,
    institucion character varying(100),
    rol character varying(20) NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    foto character varying(255),
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    autorizacion_datos boolean NOT NULL,
    embedded jsonb
);


ALTER TABLE public.users_users OWNER TO postgres;

--
-- Name: users_users_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_users_groups (
    id bigint NOT NULL,
    users_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_users_groups OWNER TO postgres;

--
-- Name: users_users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_users_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_users_user_permissions (
    id bigint NOT NULL,
    users_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_users_user_permissions OWNER TO postgres;

--
-- Name: users_users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: contenido_bibliografia contenido_bibliografia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_bibliografia
    ADD CONSTRAINT contenido_bibliografia_pkey PRIMARY KEY (id);


--
-- Name: contenido_conceptosbasicos_recursos contenido_conceptosbasic_conceptosbasicos_id_recu_e04c0524_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_conceptosbasicos_recursos
    ADD CONSTRAINT contenido_conceptosbasic_conceptosbasicos_id_recu_e04c0524_uniq UNIQUE (conceptosbasicos_id, recursos_id);


--
-- Name: contenido_conceptosbasicos contenido_conceptosbasicos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_conceptosbasicos
    ADD CONSTRAINT contenido_conceptosbasicos_pkey PRIMARY KEY (id);


--
-- Name: contenido_conceptosbasicos_recursos contenido_conceptosbasicos_recursos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_conceptosbasicos_recursos
    ADD CONSTRAINT contenido_conceptosbasicos_recursos_pkey PRIMARY KEY (id);


--
-- Name: contenido_formulas contenido_formulas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_formulas
    ADD CONSTRAINT contenido_formulas_pkey PRIMARY KEY (id);


--
-- Name: contenido_practicas contenido_practicas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_practicas
    ADD CONSTRAINT contenido_practicas_pkey PRIMARY KEY (id);


--
-- Name: contenido_procedimientos contenido_procedimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_procedimientos
    ADD CONSTRAINT contenido_procedimientos_pkey PRIMARY KEY (id);


--
-- Name: contenido_recursos contenido_recursos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_recursos
    ADD CONSTRAINT contenido_recursos_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: informes_conclusiones informes_conclusiones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.informes_conclusiones
    ADD CONSTRAINT informes_conclusiones_pkey PRIMARY KEY (id);


--
-- Name: informes_informe informes_informe_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.informes_informe
    ADD CONSTRAINT informes_informe_pkey PRIMARY KEY (id);


--
-- Name: informes_recomendaciones informes_recomendaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.informes_recomendaciones
    ADD CONSTRAINT informes_recomendaciones_pkey PRIMARY KEY (id);


--
-- Name: informes_resultado informes_resultado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.informes_resultado
    ADD CONSTRAINT informes_resultado_pkey PRIMARY KEY (id);


--
-- Name: inscripciones_inscripcion inscripciones_inscripcion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inscripciones_inscripcion
    ADD CONSTRAINT inscripciones_inscripcion_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_actividadlaboratorio laboratorios_actividadlaboratorio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_actividadlaboratorio
    ADD CONSTRAINT laboratorios_actividadlaboratorio_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_categoria laboratorios_categoria_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_categoria
    ADD CONSTRAINT laboratorios_categoria_nombre_key UNIQUE (nombre);


--
-- Name: laboratorios_categoria laboratorios_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_categoria
    ADD CONSTRAINT laboratorios_categoria_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_detalleactividad laboratorios_detalleactividad_actividad_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_detalleactividad
    ADD CONSTRAINT laboratorios_detalleactividad_actividad_id_key UNIQUE (actividad_id);


--
-- Name: laboratorios_detalleactividad laboratorios_detalleactividad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_detalleactividad
    ADD CONSTRAINT laboratorios_detalleactividad_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_etapa laboratorios_etapa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_etapa
    ADD CONSTRAINT laboratorios_etapa_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_laboratorio laboratorios_laboratorio_codigo_lab_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorio
    ADD CONSTRAINT laboratorios_laboratorio_codigo_lab_key UNIQUE (codigo_lab);


--
-- Name: laboratorios_laboratorio_palabras_clave laboratorios_laboratorio_laboratorio_id_palabracl_152d1134_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorio_palabras_clave
    ADD CONSTRAINT laboratorios_laboratorio_laboratorio_id_palabracl_152d1134_uniq UNIQUE (laboratorio_id, palabraclave_id);


--
-- Name: laboratorios_laboratorioprofesor_recursos laboratorios_laboratorio_laboratorioprofesor_id_r_72a86b53_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorioprofesor_recursos
    ADD CONSTRAINT laboratorios_laboratorio_laboratorioprofesor_id_r_72a86b53_uniq UNIQUE (laboratorioprofesor_id, recursos_id);


--
-- Name: laboratorios_laboratorio_palabras_clave laboratorios_laboratorio_palabras_clave_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorio_palabras_clave
    ADD CONSTRAINT laboratorios_laboratorio_palabras_clave_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_laboratorio laboratorios_laboratorio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorio
    ADD CONSTRAINT laboratorios_laboratorio_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_laboratorioprofesor laboratorios_laboratorioprofesor_codigo_lab_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorioprofesor
    ADD CONSTRAINT laboratorios_laboratorioprofesor_codigo_lab_key UNIQUE (codigo_lab);


--
-- Name: laboratorios_laboratorioprofesor laboratorios_laboratorioprofesor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorioprofesor
    ADD CONSTRAINT laboratorios_laboratorioprofesor_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_laboratorioprofesor_recursos laboratorios_laboratorioprofesor_recursos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorioprofesor_recursos
    ADD CONSTRAINT laboratorios_laboratorioprofesor_recursos_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_objetivo laboratorios_objetivo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_objetivo
    ADD CONSTRAINT laboratorios_objetivo_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_palabraclave laboratorios_palabraclave_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_palabraclave
    ADD CONSTRAINT laboratorios_palabraclave_pkey PRIMARY KEY (id);


--
-- Name: laboratorios_progresoestudiante laboratorios_progresoest_estudiante_id_etapa_id_db08a455_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_progresoestudiante
    ADD CONSTRAINT laboratorios_progresoest_estudiante_id_etapa_id_db08a455_uniq UNIQUE (estudiante_id, etapa_id);


--
-- Name: laboratorios_progresoestudiante laboratorios_progresoestudiante_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_progresoestudiante
    ADD CONSTRAINT laboratorios_progresoestudiante_pkey PRIMARY KEY (id);


--
-- Name: notificaciones_log notificaciones_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones_log
    ADD CONSTRAINT notificaciones_log_pkey PRIMARY KEY (id);


--
-- Name: notificaciones_notificacion notificaciones_notificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones_notificacion
    ADD CONSTRAINT notificaciones_notificacion_pkey PRIMARY KEY (id);


--
-- Name: parametros_parametro parametros_parametro_clave_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametros_parametro
    ADD CONSTRAINT parametros_parametro_clave_key UNIQUE (clave);


--
-- Name: parametros_parametro parametros_parametro_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametros_parametro
    ADD CONSTRAINT parametros_parametro_pkey PRIMARY KEY (id);


--
-- Name: reportes_reportelaboratorio_estudiantes reportes_reportelaborato_reportelaboratorio_id_us_0f29e688_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reportes_reportelaboratorio_estudiantes
    ADD CONSTRAINT reportes_reportelaborato_reportelaboratorio_id_us_0f29e688_uniq UNIQUE (reportelaboratorio_id, users_id);


--
-- Name: reportes_reportelaboratorio_estudiantes reportes_reportelaboratorio_estudiantes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reportes_reportelaboratorio_estudiantes
    ADD CONSTRAINT reportes_reportelaboratorio_estudiantes_pkey PRIMARY KEY (id);


--
-- Name: reportes_reportelaboratorio reportes_reportelaboratorio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reportes_reportelaboratorio
    ADD CONSTRAINT reportes_reportelaboratorio_pkey PRIMARY KEY (id);


--
-- Name: users_users users_users_correo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users
    ADD CONSTRAINT users_users_correo_key UNIQUE (correo);


--
-- Name: users_users_groups users_users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users_groups
    ADD CONSTRAINT users_users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_users_groups users_users_groups_users_id_group_id_02603a5e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users_groups
    ADD CONSTRAINT users_users_groups_users_id_group_id_02603a5e_uniq UNIQUE (users_id, group_id);


--
-- Name: users_users users_users_identificacion_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users
    ADD CONSTRAINT users_users_identificacion_key UNIQUE (identificacion);


--
-- Name: users_users users_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users
    ADD CONSTRAINT users_users_pkey PRIMARY KEY (id);


--
-- Name: users_users_user_permissions users_users_user_permiss_users_id_permission_id_119659d5_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users_user_permissions
    ADD CONSTRAINT users_users_user_permiss_users_id_permission_id_119659d5_uniq UNIQUE (users_id, permission_id);


--
-- Name: users_users_user_permissions users_users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users_user_permissions
    ADD CONSTRAINT users_users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: contenido_bibliografia_laboratorio_id_2c182ce9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contenido_bibliografia_laboratorio_id_2c182ce9 ON public.contenido_bibliografia USING btree (laboratorio_id);


--
-- Name: contenido_conceptosbasicos_conceptosbasicos_id_f794669d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contenido_conceptosbasicos_conceptosbasicos_id_f794669d ON public.contenido_conceptosbasicos_recursos USING btree (conceptosbasicos_id);


--
-- Name: contenido_conceptosbasicos_recursos_recursos_id_5243a857; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contenido_conceptosbasicos_recursos_recursos_id_5243a857 ON public.contenido_conceptosbasicos_recursos USING btree (recursos_id);


--
-- Name: contenido_formulas_laboratorio_id_ca35a923; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contenido_formulas_laboratorio_id_ca35a923 ON public.contenido_formulas USING btree (laboratorio_id);


--
-- Name: contenido_practicas_laboratorio_id_01dffc64; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contenido_practicas_laboratorio_id_01dffc64 ON public.contenido_practicas USING btree (laboratorio_id);


--
-- Name: contenido_procedimientos_laboratorio_id_e3105e67; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contenido_procedimientos_laboratorio_id_e3105e67 ON public.contenido_procedimientos USING btree (laboratorio_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: informes_conclusiones_informe_id_ca070628; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX informes_conclusiones_informe_id_ca070628 ON public.informes_conclusiones USING btree (informe_id);


--
-- Name: informes_informe_autor_id_098d8973; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX informes_informe_autor_id_098d8973 ON public.informes_informe USING btree (autor_id);


--
-- Name: informes_informe_laboratorio_id_a6397a28; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX informes_informe_laboratorio_id_a6397a28 ON public.informes_informe USING btree (laboratorio_id);


--
-- Name: informes_recomendaciones_informe_id_1d957564; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX informes_recomendaciones_informe_id_1d957564 ON public.informes_recomendaciones USING btree (informe_id);


--
-- Name: informes_resultado_informe_id_c8f87e52; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX informes_resultado_informe_id_c8f87e52 ON public.informes_resultado USING btree (informe_id);


--
-- Name: inscripciones_inscripcion_laboratorio_id_037064cc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inscripciones_inscripcion_laboratorio_id_037064cc ON public.inscripciones_inscripcion USING btree (laboratorio_id);


--
-- Name: inscripciones_inscripcion_usuario_id_481272be; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inscripciones_inscripcion_usuario_id_481272be ON public.inscripciones_inscripcion USING btree (usuario_id);


--
-- Name: laboratorios_actividadlaboratorio_laboratorio_id_693db0d2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_actividadlaboratorio_laboratorio_id_693db0d2 ON public.laboratorios_actividadlaboratorio USING btree (laboratorio_id);


--
-- Name: laboratorios_categoria_nombre_55665a09_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_categoria_nombre_55665a09_like ON public.laboratorios_categoria USING btree (nombre varchar_pattern_ops);


--
-- Name: laboratorios_etapa_laboratorio_id_7401d444; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_etapa_laboratorio_id_7401d444 ON public.laboratorios_etapa USING btree (laboratorio_id);


--
-- Name: laboratorios_laboratorio_categoria_id_30350c19; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratorio_categoria_id_30350c19 ON public.laboratorios_laboratorio USING btree (categoria_id);


--
-- Name: laboratorios_laboratorio_codigo_lab_975e264b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratorio_codigo_lab_975e264b_like ON public.laboratorios_laboratorio USING btree (codigo_lab varchar_pattern_ops);


--
-- Name: laboratorios_laboratorio_creador_id_01762db1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratorio_creador_id_01762db1 ON public.laboratorios_laboratorio USING btree (creador_id);


--
-- Name: laboratorios_laboratorio_objetivo_id_6562b9e6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratorio_objetivo_id_6562b9e6 ON public.laboratorios_laboratorio USING btree (objetivo_id);


--
-- Name: laboratorios_laboratorio_p_palabraclave_id_8ecb6361; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratorio_p_palabraclave_id_8ecb6361 ON public.laboratorios_laboratorio_palabras_clave USING btree (palabraclave_id);


--
-- Name: laboratorios_laboratorio_palabras_clave_laboratorio_id_c191ec0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratorio_palabras_clave_laboratorio_id_c191ec0e ON public.laboratorios_laboratorio_palabras_clave USING btree (laboratorio_id);


--
-- Name: laboratorios_laboratoriopr_laboratorioprofesor_id_42d832e8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratoriopr_laboratorioprofesor_id_42d832e8 ON public.laboratorios_laboratorioprofesor_recursos USING btree (laboratorioprofesor_id);


--
-- Name: laboratorios_laboratorioprofesor_codigo_lab_5088773e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratorioprofesor_codigo_lab_5088773e_like ON public.laboratorios_laboratorioprofesor USING btree (codigo_lab varchar_pattern_ops);


--
-- Name: laboratorios_laboratorioprofesor_laboratorio_id_1b7daa53; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratorioprofesor_laboratorio_id_1b7daa53 ON public.laboratorios_laboratorioprofesor USING btree (laboratorio_id);


--
-- Name: laboratorios_laboratorioprofesor_profesor_id_43cb3ab8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratorioprofesor_profesor_id_43cb3ab8 ON public.laboratorios_laboratorioprofesor USING btree (profesor_id);


--
-- Name: laboratorios_laboratorioprofesor_recursos_recursos_id_ec3a4139; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_laboratorioprofesor_recursos_recursos_id_ec3a4139 ON public.laboratorios_laboratorioprofesor_recursos USING btree (recursos_id);


--
-- Name: laboratorios_palabraclave_categoria_id_56a7ede4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_palabraclave_categoria_id_56a7ede4 ON public.laboratorios_palabraclave USING btree (categoria_id);


--
-- Name: laboratorios_progresoestudiante_estudiante_id_658d8931; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_progresoestudiante_estudiante_id_658d8931 ON public.laboratorios_progresoestudiante USING btree (estudiante_id);


--
-- Name: laboratorios_progresoestudiante_etapa_id_80c7d312; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX laboratorios_progresoestudiante_etapa_id_80c7d312 ON public.laboratorios_progresoestudiante USING btree (etapa_id);


--
-- Name: notificaciones_log_usuario_id_06ecf414; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notificaciones_log_usuario_id_06ecf414 ON public.notificaciones_log USING btree (usuario_id);


--
-- Name: notificaciones_notificacion_usuario_id_4bc090a3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notificaciones_notificacion_usuario_id_4bc090a3 ON public.notificaciones_notificacion USING btree (usuario_id);


--
-- Name: parametros_parametro_clave_b667771f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parametros_parametro_clave_b667771f_like ON public.parametros_parametro USING btree (clave varchar_pattern_ops);


--
-- Name: reportes_reportelaboratori_reportelaboratorio_id_641acd13; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reportes_reportelaboratori_reportelaboratorio_id_641acd13 ON public.reportes_reportelaboratorio_estudiantes USING btree (reportelaboratorio_id);


--
-- Name: reportes_reportelaboratorio_estudiantes_users_id_82fb1c5c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reportes_reportelaboratorio_estudiantes_users_id_82fb1c5c ON public.reportes_reportelaboratorio_estudiantes USING btree (users_id);


--
-- Name: reportes_reportelaboratorio_laboratorio_profesor_id_85711bbc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reportes_reportelaboratorio_laboratorio_profesor_id_85711bbc ON public.reportes_reportelaboratorio USING btree (laboratorio_profesor_id);


--
-- Name: users_users_correo_61973af2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_users_correo_61973af2_like ON public.users_users USING btree (correo varchar_pattern_ops);


--
-- Name: users_users_groups_group_id_3e15ff0f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_users_groups_group_id_3e15ff0f ON public.users_users_groups USING btree (group_id);


--
-- Name: users_users_groups_users_id_5572cf36; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_users_groups_users_id_5572cf36 ON public.users_users_groups USING btree (users_id);


--
-- Name: users_users_identificacion_c6ee061b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_users_identificacion_c6ee061b_like ON public.users_users USING btree (identificacion varchar_pattern_ops);


--
-- Name: users_users_user_permissions_permission_id_9a117d64; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_users_user_permissions_permission_id_9a117d64 ON public.users_users_user_permissions USING btree (permission_id);


--
-- Name: users_users_user_permissions_users_id_04010ba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_users_user_permissions_users_id_04010ba6 ON public.users_users_user_permissions USING btree (users_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contenido_bibliografia contenido_bibliografia_laboratorio_id_2c182ce9_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_bibliografia
    ADD CONSTRAINT contenido_bibliografia_laboratorio_id_2c182ce9_fk FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios_laboratorio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contenido_conceptosbasicos_recursos contenido_conceptosb_conceptosbasicos_id_f794669d_fk_contenido; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_conceptosbasicos_recursos
    ADD CONSTRAINT contenido_conceptosb_conceptosbasicos_id_f794669d_fk_contenido FOREIGN KEY (conceptosbasicos_id) REFERENCES public.contenido_conceptosbasicos(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contenido_conceptosbasicos_recursos contenido_conceptosb_recursos_id_5243a857_fk_contenido; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_conceptosbasicos_recursos
    ADD CONSTRAINT contenido_conceptosb_recursos_id_5243a857_fk_contenido FOREIGN KEY (recursos_id) REFERENCES public.contenido_recursos(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contenido_formulas contenido_formulas_laboratorio_id_ca35a923_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_formulas
    ADD CONSTRAINT contenido_formulas_laboratorio_id_ca35a923_fk FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios_laboratorio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contenido_practicas contenido_practicas_laboratorio_id_01dffc64_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_practicas
    ADD CONSTRAINT contenido_practicas_laboratorio_id_01dffc64_fk FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios_laboratorio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contenido_procedimientos contenido_procedimientos_laboratorio_id_e3105e67_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contenido_procedimientos
    ADD CONSTRAINT contenido_procedimientos_laboratorio_id_e3105e67_fk FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios_laboratorio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_users_id FOREIGN KEY (user_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: informes_conclusiones informes_conclusiones_informe_id_ca070628_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.informes_conclusiones
    ADD CONSTRAINT informes_conclusiones_informe_id_ca070628_fk FOREIGN KEY (informe_id) REFERENCES public.informes_informe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: informes_informe informes_informe_autor_id_098d8973_fk_users_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.informes_informe
    ADD CONSTRAINT informes_informe_autor_id_098d8973_fk_users_users_id FOREIGN KEY (autor_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: informes_informe informes_informe_laboratorio_id_a6397a28_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.informes_informe
    ADD CONSTRAINT informes_informe_laboratorio_id_a6397a28_fk FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios_laboratorio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: informes_recomendaciones informes_recomendaciones_informe_id_1d957564_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.informes_recomendaciones
    ADD CONSTRAINT informes_recomendaciones_informe_id_1d957564_fk FOREIGN KEY (informe_id) REFERENCES public.informes_informe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: informes_resultado informes_resultado_informe_id_c8f87e52_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.informes_resultado
    ADD CONSTRAINT informes_resultado_informe_id_c8f87e52_fk FOREIGN KEY (informe_id) REFERENCES public.informes_informe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inscripciones_inscripcion inscripciones_inscri_laboratorio_id_037064cc_fk_laborator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inscripciones_inscripcion
    ADD CONSTRAINT inscripciones_inscri_laboratorio_id_037064cc_fk_laborator FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios_laboratorioprofesor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inscripciones_inscripcion inscripciones_inscripcion_usuario_id_481272be_fk_users_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inscripciones_inscripcion
    ADD CONSTRAINT inscripciones_inscripcion_usuario_id_481272be_fk_users_users_id FOREIGN KEY (usuario_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_actividadlaboratorio laboratorios_activid_laboratorio_id_693db0d2_fk_laborator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_actividadlaboratorio
    ADD CONSTRAINT laboratorios_activid_laboratorio_id_693db0d2_fk_laborator FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios_laboratorioprofesor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_detalleactividad laboratorios_detalle_actividad_id_1e36bbe3_fk_laborator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_detalleactividad
    ADD CONSTRAINT laboratorios_detalle_actividad_id_1e36bbe3_fk_laborator FOREIGN KEY (actividad_id) REFERENCES public.laboratorios_actividadlaboratorio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_etapa laboratorios_etapa_laboratorio_id_7401d444_fk_laborator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_etapa
    ADD CONSTRAINT laboratorios_etapa_laboratorio_id_7401d444_fk_laborator FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios_laboratorioprofesor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_laboratorioprofesor laboratorios_laborat_laboratorio_id_1b7daa53_fk_laborator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorioprofesor
    ADD CONSTRAINT laboratorios_laborat_laboratorio_id_1b7daa53_fk_laborator FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios_laboratorio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_laboratorioprofesor_recursos laboratorios_laborat_laboratorioprofesor__42d832e8_fk_laborator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorioprofesor_recursos
    ADD CONSTRAINT laboratorios_laborat_laboratorioprofesor__42d832e8_fk_laborator FOREIGN KEY (laboratorioprofesor_id) REFERENCES public.laboratorios_laboratorioprofesor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_laboratorioprofesor laboratorios_laborat_profesor_id_43cb3ab8_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorioprofesor
    ADD CONSTRAINT laboratorios_laborat_profesor_id_43cb3ab8_fk_users_use FOREIGN KEY (profesor_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_laboratorioprofesor_recursos laboratorios_laborat_recursos_id_ec3a4139_fk_contenido; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorioprofesor_recursos
    ADD CONSTRAINT laboratorios_laborat_recursos_id_ec3a4139_fk_contenido FOREIGN KEY (recursos_id) REFERENCES public.contenido_recursos(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_laboratorio_palabras_clave laboratorios_laboratorio__laboratorio_id_c191ec0e_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorio_palabras_clave
    ADD CONSTRAINT laboratorios_laboratorio__laboratorio_id_c191ec0e_fk FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios_laboratorio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_laboratorio_palabras_clave laboratorios_laboratorio__palabraclave_id_8ecb6361_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorio_palabras_clave
    ADD CONSTRAINT laboratorios_laboratorio__palabraclave_id_8ecb6361_fk FOREIGN KEY (palabraclave_id) REFERENCES public.laboratorios_palabraclave(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_laboratorio laboratorios_laboratorio_categoria_id_30350c19_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorio
    ADD CONSTRAINT laboratorios_laboratorio_categoria_id_30350c19_fk FOREIGN KEY (categoria_id) REFERENCES public.laboratorios_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_laboratorio laboratorios_laboratorio_creador_id_01762db1_fk_users_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorio
    ADD CONSTRAINT laboratorios_laboratorio_creador_id_01762db1_fk_users_users_id FOREIGN KEY (creador_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_laboratorio laboratorios_laboratorio_objetivo_id_6562b9e6_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_laboratorio
    ADD CONSTRAINT laboratorios_laboratorio_objetivo_id_6562b9e6_fk FOREIGN KEY (objetivo_id) REFERENCES public.laboratorios_objetivo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_palabraclave laboratorios_palabraclave_categoria_id_56a7ede4_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_palabraclave
    ADD CONSTRAINT laboratorios_palabraclave_categoria_id_56a7ede4_fk FOREIGN KEY (categoria_id) REFERENCES public.laboratorios_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_progresoestudiante laboratorios_progres_estudiante_id_658d8931_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_progresoestudiante
    ADD CONSTRAINT laboratorios_progres_estudiante_id_658d8931_fk_users_use FOREIGN KEY (estudiante_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: laboratorios_progresoestudiante laboratorios_progres_etapa_id_80c7d312_fk_laborator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios_progresoestudiante
    ADD CONSTRAINT laboratorios_progres_etapa_id_80c7d312_fk_laborator FOREIGN KEY (etapa_id) REFERENCES public.laboratorios_etapa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notificaciones_log notificaciones_log_usuario_id_06ecf414_fk_users_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones_log
    ADD CONSTRAINT notificaciones_log_usuario_id_06ecf414_fk_users_users_id FOREIGN KEY (usuario_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notificaciones_notificacion notificaciones_notif_usuario_id_4bc090a3_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones_notificacion
    ADD CONSTRAINT notificaciones_notif_usuario_id_4bc090a3_fk_users_use FOREIGN KEY (usuario_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reportes_reportelaboratorio reportes_reportelabo_laboratorio_profesor_85711bbc_fk_laborator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reportes_reportelaboratorio
    ADD CONSTRAINT reportes_reportelabo_laboratorio_profesor_85711bbc_fk_laborator FOREIGN KEY (laboratorio_profesor_id) REFERENCES public.laboratorios_laboratorioprofesor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reportes_reportelaboratorio_estudiantes reportes_reportelabo_reportelaboratorio_i_641acd13_fk_reportes_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reportes_reportelaboratorio_estudiantes
    ADD CONSTRAINT reportes_reportelabo_reportelaboratorio_i_641acd13_fk_reportes_ FOREIGN KEY (reportelaboratorio_id) REFERENCES public.reportes_reportelaboratorio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reportes_reportelaboratorio_estudiantes reportes_reportelabo_users_id_82fb1c5c_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reportes_reportelaboratorio_estudiantes
    ADD CONSTRAINT reportes_reportelabo_users_id_82fb1c5c_fk_users_use FOREIGN KEY (users_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_users_groups users_users_groups_group_id_3e15ff0f_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users_groups
    ADD CONSTRAINT users_users_groups_group_id_3e15ff0f_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_users_groups users_users_groups_users_id_5572cf36_fk_users_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users_groups
    ADD CONSTRAINT users_users_groups_users_id_5572cf36_fk_users_users_id FOREIGN KEY (users_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_users_user_permissions users_users_user_per_permission_id_9a117d64_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users_user_permissions
    ADD CONSTRAINT users_users_user_per_permission_id_9a117d64_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_users_user_permissions users_users_user_per_users_id_04010ba6_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_users_user_permissions
    ADD CONSTRAINT users_users_user_per_users_id_04010ba6_fk_users_use FOREIGN KEY (users_id) REFERENCES public.users_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict R9xSIs6nin8nATeOphHvtyXLN1oe6kiczJ9v1719y4NuW08yXYBELaeNHCv8SRE

