# Generated by Django 6.0.4 on 2026-06-10 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entregas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('retroalimentacion', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_ia', to='entregas.entrega')),
            ],
            options={
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_docente', to='entregas.entrega')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
