# Generated by Django 6.0.4 on 2026-06-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='tipo_reporte',
            field=models.CharField(choices=[('PRACTICA', 'Práctica'), ('SIMULACION', 'Simulación')], default='PRACTICA', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('GENERADO', 'Generado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='ACTIVO', max_length=20),
        ),
    ]
