# Generated by Django 6.0.4 on 2026-06-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_entrega_tipo_reporte_alter_entrega_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('GENERADO', 'Generado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20),
        ),
    ]
