# Generated by Django 6.0.4 on 2026-06-27 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_alter_entrega_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together=None,
        ),

        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),

        migrations.RemoveField(
            model_name='respuesta',
            name='entrega',
        ),
        migrations.AlterModelOptions(
            name='resultadosimulacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='resultadosimulacion',
            old_name='parametros',
            new_name='raw_result',
        ),
        migrations.RemoveField(
            model_name='resultadosimulacion',
            name='conclusiones',
        ),
        migrations.RemoveField(
            model_name='resultadosimulacion',
            name='resultados',
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='ar_provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='average_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='best_attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='best_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='exit_reason',
            field=models.CharField(choices=[('completed', 'Completado'), ('max_attempts', 'Máximo de intentos'), ('user_exit', 'Salida del usuario')], default='completed', max_length=30),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='result_status',
            field=models.CharField(choices=[('completed', 'Completado'), ('abandoned', 'Abandonado'), ('in_progress', 'En progreso')], default='in_progress', max_length=30),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='run_id',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='successful_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadosimulacion',
            name='unity_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='IntentoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('hit', models.BooleanField(default=False)),
                ('power', models.FloatField()),
                ('angle', models.FloatField()),
                ('impact_distance', models.FloatField()),
                ('impact_horizontal_distance', models.FloatField()),
                ('impact_distance_to_target', models.FloatField()),
                ('impact_height', models.FloatField()),
                ('impact_type', models.CharField(choices=[('HitTarget', 'Hit Target'), ('MissedTarget', 'Missed Target')], max_length=30)),
                ('impact_x', models.FloatField()),
                ('impact_y', models.FloatField()),
                ('impact_z', models.FloatField()),
                ('target_x', models.FloatField()),
                ('target_y', models.FloatField()),
                ('target_z', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='entregas.resultadosimulacion')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('resultado', 'numero')},
            },
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
