# Generated by Django 6.0.4 on 2026-07-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0004_remove_respuesta_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadopractica',
            name='datos_obtenidos',
            field=models.JSONField(),
        ),
    ]
