# Generated by Django 6.0.4 on 2026-07-10 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0005_alter_resultadopractica_datos_obtenidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='tipo_reporte',
            field=models.CharField(choices=[('PRACTICA', 'Práctica'), ('SIMULACION', 'Simulación'), ('INTEGRADA', 'Entrega integrada')], default='PRACTICA', max_length=20),
        ),
        migrations.CreateModel(
            name='EntregaLaboratorioUnificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.JSONField(blank=True, default=dict)),
                ('simulation', models.JSONField(blank=True, default=dict)),
                ('comparison', models.JSONField(blank=True, default=dict)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('device', models.JSONField(blank=True, default=dict)),
                ('llm_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_unificada', to='entregas.entrega')),
            ],
        ),
    ]
