# Generated by Django 6.0.3 on 2026-04-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desarrollo', models.TextField()),
                ('resultado', models.TextField()),
                ('analisis', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('conclusiones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.conclusiones')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.laboratorio')),
                ('recomendaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.recomendaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(max_length=50)),
                ('instrumento', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='informes.informe')),
            ],
        ),
    ]
