# Generated by Django 6.0.3 on 2026-03-30 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='conclusiones',
            name='informe',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='recomendaciones',
            name='informe',
        ),
        migrations.AddField(
            model_name='informe',
            name='analisis',
            field=models.TextField(default='Sin analisis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='conclusiones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='informes.conclusiones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='desarrollo',
            field=models.TextField(default='Sin desarrollo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='recomendaciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='informes.recomendaciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='resultado',
            field=models.TextField(default='Sin resultado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.laboratorio'),
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
