# Generated by Django 6.0.3 on 2026-03-31 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_laboratorio_remove_conclusiones_informe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(max_length=50)),
                ('instrumento', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='informes.informe')),
            ],
        ),
    ]
