# Generated by Django 6.0.4 on 2026-04-11 02:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_alter_conclusiones_id_alter_informe_id_and_more'),
        ('laboratorios', '0003_alter_categoria_id_alter_laboratorio_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorio'),
        ),
        migrations.RemoveField(
            model_name='informe',
            name='conclusiones',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='recomendaciones',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='resultado',
        ),
        migrations.AddField(
            model_name='conclusiones',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conclusiones',
            name='importancia',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conclusiones',
            name='informe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conclusiones', to='informes.informe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='informe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='informes.informe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='prioridad',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conclusiones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recomendaciones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Laboratorio',
        ),
    ]
