# Generated by Django 6.0.4 on 2026-06-05 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='ReporteLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_informe', models.CharField(choices=[('Generado', 'Generado'), ('Pendiente', 'Pendiente')], default='Generado', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('reporte_estudiante', models.FileField(blank=True, null=True, upload_to='reportes/estudiantes/')),
                ('observaciones_docente', models.TextField(blank=True, null=True)),
                ('informe_final', models.FileField(blank=True, null=True, upload_to='reportes/finales/')),
                ('estudiantes', models.ManyToManyField(related_name='reportes_estudiante', to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='laboratorios.laboratorio')),
            ],
        ),
    ]
