# Generated by Django 6.0.4 on 2026-05-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
        ('laboratorios', '0004_laboratorioprofesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.laboratorioprofesor'),
        ),
    ]
