# Generated by Django 5.2.12 on 2026-03-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptosBasicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('concepto', models.CharField(max_length=100)),
                ('ejemplo', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Practicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_practica', models.CharField(max_length=100)),
                ('concepto', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('descripcion', models.TextField()),
                ('materiales', models.TextField()),
                ('calculos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio_id', models.IntegerField()),
                ('muestras', models.TextField()),
                ('calculos', models.TextField()),
                ('resultados', models.TextField()),
            ],
        ),
    ]
