# Generated by Django 6.0.4 on 2026-07-09 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
        ('laboratorios', '0029_grupoacademico_codigo_ingreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'asignacion'), name='unique_estudiante_asignacion'),
        ),
        migrations.AddField(
            model_name='grupoestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupoestudiante',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_inscritos', to='laboratorios.grupoacademico'),
        ),
        migrations.AddConstraint(
            model_name='grupoestudiante',
            constraint=models.UniqueConstraint(fields=('estudiante', 'grupo'), name='unique_estudiante_grupo'),
        ),
    ]
