# Generated by Django 5.2.12 on 2026-04-11 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_bibliografia_formulas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bibliografia',
        ),
        migrations.DeleteModel(
            name='ConceptosBasicos',
        ),
        migrations.DeleteModel(
            name='Formulas',
        ),
        migrations.DeleteModel(
            name='Practicas',
        ),
        migrations.DeleteModel(
            name='Procedimientos',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='estudiante',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
