# Generated by Django 5.2.13 on 2026-04-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_conceptosbasicos_practicas_procedimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
