# Generated by Django 6.0.3 on 2026-04-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_alter_inscripcion_id'),
        ('inscripciones', '0002_conceptosbasicos_practicas_procedimientos'),
    ]

    operations = [
    ]
