# Generated by Django 5.2.12 on 2026-04-14 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.objetivo'),
        ),
        migrations.AddField(
            model_name='palabraclave',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.categoria'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='palabras_clave',
            field=models.ManyToManyField(to='laboratorios.palabraclave'),
        ),
    ]
