# Generated by Django 6.0.4 on 2026-05-08 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_recursos_conceptosbasicos_recursos'),
        ('laboratorios', '0003_categoria_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lab', models.CharField(max_length=10, unique=True)),
                ('resumen', models.TextField()),
                ('prologo', models.TextField(blank=True, null=True)),
                ('introduccion', models.TextField()),
                ('marco_teorico', models.TextField()),
                ('generado_ia', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='laboratorios.laboratorio')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios_profesor', to=settings.AUTH_USER_MODEL)),
                ('recursos', models.ManyToManyField(blank=True, to='contenido.recursos')),
            ],
        ),
    ]
