# Generated by Django 6.0.4 on 2026-05-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0004_laboratorioprofesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorioprofesor',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
