# Generated by Django 6.0.4 on 2026-05-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0006_etapa_progresoestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorioprofesor',
            name='grado',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='laboratorioprofesor',
            name='jornada',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
