# Generated by Django 6.0.4 on 2026-05-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0007_laboratorioprofesor_grado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresoestudiante',
            name='estado',
            field=models.CharField(default='En progreso', max_length=30),
        ),
        migrations.AddField(
            model_name='progresoestudiante',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
