# Generated by Django 6.0.4 on 2026-05-28 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0007_laboratorioprofesor_grado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=20)),
                ('descripcion', models.TextField()),
                ('generado_ia', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='laboratorios.laboratorioprofesor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_especifico', models.TextField()),
                ('materiales', models.JSONField()),
                ('procedimiento', models.JSONField()),
                ('formula', models.TextField(blank=True, null=True)),
                ('tiempo_estimado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='laboratorios.actividadlaboratorio')),
            ],
        ),
    ]
