# Generated by Django 6.0.4 on 2026-05-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0008_actividadlaboratorio_detalleactividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='ra',
        ),
        migrations.AddField(
            model_name='laboratorioprofesor',
            name='simulacion',
            field=models.BooleanField(default=False),
        ),
    ]
