# Generated by Django 6.0.4 on 2026-05-29 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0009_remove_laboratorio_ra_laboratorioprofesor_simulacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='codigo_lab',
        ),
    ]
