# Generated by Django 6.0.4 on 2026-06-04 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0010_remove_laboratorio_codigo_lab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='codigo_lab',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='generado_ia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='grado',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='id_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copias', to='laboratorios.laboratorio'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='jornada',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorios_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='simulacion',
            field=models.BooleanField(default=False),
        ),
    ]
