# Generated by Django 6.0.4 on 2026-06-05 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0011_laboratorio_codigo_lab_laboratorio_generado_ia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadlaboratorio',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='laboratorios.laboratorio'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='laboratorios.laboratorio'),
        ),
        migrations.DeleteModel(
            name='LaboratorioProfesor',
        ),
    ]
