# Generated by Django 6.0.4 on 2026-06-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_remove_practicas_concepto_practicas_conceptos_and_more'),
        ('laboratorios', '0012_alter_actividadlaboratorio_laboratorio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleactividad',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='objetivo',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='conceptos_basicos',
            field=models.ManyToManyField(blank=True, to='contenido.conceptosbasicos'),
        ),
        migrations.CreateModel(
            name='ObjetivoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('laboratorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_general', to='laboratorios.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('objetivo_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_especificos', to='laboratorios.objetivogeneral')),
            ],
        ),
        migrations.DeleteModel(
            name='ActividadLaboratorio',
        ),
        migrations.DeleteModel(
            name='DetalleActividad',
        ),
        migrations.DeleteModel(
            name='Objetivo',
        ),
    ]
