# Generated by Django 6.0.4 on 2026-06-09 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_plantillabibliografia_plantillaformula_and_more'),
        ('laboratorios', '0013_remove_detalleactividad_actividad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='etapa',
            name='tipo',
            field=models.CharField(choices=[('CONCEPTOS', 'Conceptos Básicos'), ('PRACTICA', 'Práctica'), ('INFORME', 'Informe')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etapa',
            name='orden',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='codigo_lab',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='conceptos_basicos',
            field=models.ManyToManyField(blank=True, related_name='laboratorios', to='contenido.conceptosbasicos'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='palabras_clave',
            field=models.ManyToManyField(blank=True, related_name='laboratorios', to='laboratorios.palabraclave'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='palabraclave',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras_clave', to='laboratorios.categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('laboratorio', 'tipo')},
        ),
        migrations.CreateModel(
            name='GrupoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=20)),
                ('jornada', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'profesor')},
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='laboratorios.laboratorio')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='laboratorios.grupoacademico')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'unique_together': {('laboratorio', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='PlantillaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField()),
                ('prologo', models.TextField(blank=True, null=True)),
                ('introduccion', models.TextField()),
                ('marco_teorico', models.TextField()),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('simulacion', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='laboratorios.categoria')),
                ('conceptos_basicos', models.ManyToManyField(blank=True, related_name='plantillas', to='contenido.conceptosbasicos')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL)),
                ('palabras_clave', models.ManyToManyField(blank=True, related_name='plantillas', to='laboratorios.palabraclave')),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='plantilla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='laboratorios.plantillalaboratorio'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='laboratorio',
            unique_together={('plantilla', 'profesor')},
        ),
        migrations.CreateModel(
            name='PlantillaObjetivoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('plantilla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_general', to='laboratorios.plantillalaboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaObjetivoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('objetivo_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_especificos', to='laboratorios.plantillaobjetivogeneral')),
            ],
        ),
        migrations.DeleteModel(
            name='ProgresoEstudiante',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='id_padre',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='simulacion',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='titulo_lab',
        ),
    ]
