# Generated by Django 6.0.4 on 2026-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0014_alter_etapa_options_alter_laboratorio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='codigo_lab',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='codigo_ingreso',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='codigo_ingreso',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
