# Generated by Django 6.0.4 on 2026-06-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0015_remove_laboratorio_codigo_lab_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laboratorio',
            unique_together=set(),
        ),
    ]
