# Generated by Django 6.0.4 on 2026-06-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0016_alter_laboratorio_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='codigo_ingreso',
        ),
    ]
