# Generated by Django 6.0.4 on 2026-06-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0017_remove_laboratorio_codigo_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='BORRADOR', max_length=20),
        ),
    ]
