# Generated by Django 6.0.4 on 2026-06-19 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_remove_plantillabibliografia_plantilla_and_more'),
        ('laboratorios', '0017_remove_laboratorio_codigo_ingreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palabraclave',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='plantillalaboratorio',
            name='palabras_clave',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='palabras_clave',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='jornada',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='prologo',
        ),
        migrations.RemoveField(
            model_name='plantillalaboratorio',
            name='prologo',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantillalaboratorio',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='laboratorio',
            constraint=models.UniqueConstraint(fields=('plantilla', 'profesor'), name='unique_plantilla_profesor'),
        ),
        migrations.DeleteModel(
            name='PalabraClave',
        ),
    ]
