# Generated by Django 6.0.4 on 2026-06-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0018_remove_palabraclave_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='profesor',
        ),
    ]
