# Generated by Django 6.0.4 on 2026-06-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0019_remove_asignacion_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillalaboratorio',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
