# Generated by Django 6.0.4 on 2026-06-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0020_alter_plantillalaboratorio_titulo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='laboratorio',
            name='unique_plantilla_profesor',
        ),
    ]
