# Generated by Django 6.0.4 on 2026-06-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0021_remove_laboratorio_unique_plantilla_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='simulacion_ar',
            field=models.JSONField(blank=True, help_text='Configuración de Unity AR', null=True),
        ),
    ]
