# Generated by Django 6.0.4 on 2026-06-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0022_laboratorio_simulacion_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='simulacion_ar',
        ),
        migrations.RemoveField(
            model_name='plantillalaboratorio',
            name='simulacion',
        ),
        migrations.AddField(
            model_name='plantillalaboratorio',
            name='lab_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
