# Generated by Django 6.0.4 on 2026-06-28 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0023_remove_laboratorio_simulacion_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='tipo',
            field=models.CharField(choices=[('INTRODUCTION', 'Introducción'), ('THEORY', 'Marco Teórico'), ('OBJECTIVES', 'Objetivos'), ('CONCEPTS', 'Conceptos Básicos'), ('FORMULAS', 'Fórmulas'), ('PRACTICE', 'Práctica'), ('SIMULATION_AR', 'Simulación AR'), ('COMPARISON', 'Comparación'), ('REPORT', 'Informe'), ('SUBMIT', 'Envío')], max_length=30),
        ),
        migrations.CreateModel(
            name='PlantillaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INTRODUCTION', 'Introducción'), ('THEORY', 'Marco Teórico'), ('OBJECTIVES', 'Objetivos'), ('CONCEPTS', 'Conceptos Básicos'), ('FORMULAS', 'Fórmulas'), ('PRACTICE', 'Práctica'), ('SIMULATION_AR', 'Simulación AR'), ('COMPARISON', 'Comparación'), ('REPORT', 'Informe'), ('SUBMIT', 'Envío')], max_length=30)),
                ('orden', models.PositiveSmallIntegerField()),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='laboratorios.plantillalaboratorio')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('plantilla', 'tipo')},
            },
        ),
    ]
