# Generated by Django 6.0.4 on 2026-06-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0024_alter_etapa_tipo_plantillaetapa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantillaEtapa',
        ),
    ]
