# Generated by Django 6.0.4 on 2026-06-29 05:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0025_delete_plantillaetapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillalaboratorio',
            name='imagen_portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
