# Generated by Django 6.0.4 on 2026-07-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0026_plantillalaboratorio_imagen_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillalaboratorio',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
