# Generated by Django 6.0.4 on 2026-07-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0027_plantillalaboratorio_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='conceptos_basicos',
        ),
    ]
