# Generated by Django 6.0.4 on 2026-07-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0028_remove_laboratorio_conceptos_basicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoacademico',
            name='codigo_ingreso',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
    ]
