# Generated by Django 6.0.4 on 2026-07-10 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0029_grupoacademico_codigo_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('unity_scene_name', models.CharField(blank=True, default='', max_length=150)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('version', models.CharField(blank=True, default='1.0.0', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('intro_title', models.CharField(blank=True, default='', max_length=200)),
                ('intro_text', models.TextField(blank=True, default='')),
                ('instructions', models.JSONField(blank=True, default=list)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('allow_resume', models.BooleanField(default=True)),
                ('requires_camera', models.BooleanField(default=True)),
                ('formulas', models.JSONField(blank=True, default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('result_schema', models.JSONField(blank=True, default=dict)),
                ('evaluation_context', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('laboratorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulacion_ar_config', to='laboratorios.laboratorio')),
            ],
            options={
                'ordering': ['lab_key', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SABER', 'Saber'), ('SABER_HACER', 'Saber hacer'), ('ANALISIS', 'Análisis'), ('REFLEXION', 'Reflexión'), ('CIERRE', 'Cierre')], default='ANALISIS', max_length=30)),
                ('key', models.CharField(max_length=100)),
                ('titulo', models.CharField(blank=True, default='', max_length=200)),
                ('enunciado', models.TextField(blank=True, default='')),
                ('input_type', models.CharField(choices=[('TEXT', 'Texto'), ('TEXTAREA', 'Texto largo'), ('NUMBER', 'Número'), ('BOOLEAN', 'Booleano'), ('SELECT', 'Selección'), ('MULTI_SELECT', 'Selección múltiple')], default='TEXTAREA', max_length=30)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('options', models.JSONField(blank=True, default=list)),
                ('evaluation_hint', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='laboratorios.laboratorio')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('laboratorio', 'key')},
            },
        ),
    ]
